// action types
export const SIGN_IN_CANCEL = 'SIGNIN_CANCEL'

// async action types
export const LOADING_AUTH_USER = 'LOADING_AUTH_USER'
export const LOADING_AUTH_USER_SUCCEEDED = 'LOADING_AUTH_USER_SUCCEEDED'
export const LOADING_AUTH_USER_FAILED = 'LOADING_AUTH_USER_FAILED'
export const SIGNING_IN = 'SIGNING_IN'
export const SIGNING_IN_SUCCEEDED = 'SIGNING_IN_SUCCEEDED'
export const SIGNING_IN_FAILED = 'SIGNING_IN_FAILED'
export const SIGNING_OUT = 'SIGNING_OUT'
export const SIGNING_OUT_SUCCEEDED = 'SIGNING_OUT_SUCCEEDED'
export const SIGNING_OUT_FAILED = 'SIGNING_OUT_FAILED'
export const LOADING_INVOICES = 'LOADING_INVOICES'
export const LOADING_INVOICES_SUCCEEDED = 'LOADING_INVOICES_SUCCEEDED'
export const LOADING_INVOICES_FAILED = 'LOADING_INVOICES_FAILED'
export const CREATING_INVOICE = 'CREATING_INVOICE'
export const CREATING_INVOICE_SUCCEEDED = 'CREATING_INVOICE_SUCCEEDED'
export const CREATING_INVOICE_FAILED = 'CREATING_INVOICE_FAILED'
export const DELETING_INVOICE = 'DELETING_INVOICE'
export const DELETING_INVOICE_SUCCEEDED = 'DELETING_INVOICE_SUCCEEDED'
export const DELETING_INVOICE_FAILED = 'DELETING_INVOICE_FAILED'

// route params
export const INVOICE_ID_PARAM = 'invoiceId'
export const INVOICE_ITEM_ID_PARAM = 'invoiceItemId'
export const USER_ID_PARAM = 'userId'
