// action types

export const SIGN_IN_CANCEL = 'SIGNIN_CANCEL'

// async action types

export const LOADING_AUTH_USER = 'LOADING_AUTH_USER'
export const LOADING_AUTH_USER_SUCCEEDED = 'LOADING_AUTH_USER_SUCCEEDED'
export const LOADING_AUTH_USER_FAILED = 'LOADING_AUTH_USER_FAILED'

export const SIGNING_IN = 'SIGNING_IN'
export const SIGNING_IN_SUCCEEDED = 'SIGNING_IN_SUCCEEDED'
export const SIGNING_IN_FAILED = 'SIGNING_IN_FAILED'

export const SIGNING_OUT = 'SIGNING_OUT'
export const SIGNING_OUT_SUCCEEDED = 'SIGNING_OUT_SUCCEEDED'
export const SIGNING_OUT_FAILED = 'SIGNING_OUT_FAILED'

export const LOADING_INVOICES = 'LOADING_INVOICES'
export const LOADING_INVOICES_SUCCEEDED = 'LOADING_INVOICES_SUCCEEDED'
export const LOADING_INVOICES_FAILED = 'LOADING_INVOICES_FAILED'

export const CREATING_INVOICE = 'CREATING_INVOICE'
export const CREATING_INVOICE_SUCCEEDED = 'CREATING_INVOICE_SUCCEEDED'
export const CREATING_INVOICE_FAILED = 'CREATING_INVOICE_FAILED'

export const UPDATING_INVOICE = 'UPDATING_INVOICE'
export const UPDATING_INVOICE_SUCCEEDED = 'UPDATING_INVOICE_SUCCEEDED'
export const UPDATING_INVOICE_FAILED = 'UPDATING_INVOICE_FAILED'

export const DELETING_INVOICE = 'DELETING_INVOICE'
export const DELETING_INVOICE_SUCCEEDED = 'DELETING_INVOICE_SUCCEEDED'
export const DELETING_INVOICE_FAILED = 'DELETING_INVOICE_FAILED'

export const CREATING_INVOICE_ITEM = 'CREATING_INVOICE_ITEM'
export const CREATING_INVOICE_ITEM_SUCCEEDED = 'CREATING_INVOICE_ITEM_SUCCEEDED'
export const CREATING_INVOICE_ITEM_FAILED = 'CREATING_INVOICE_ITEM_FAILED'

export const UPDATING_INVOICE_ITEM = 'UPDATING_INVOICE_ITEM'
export const UPDATING_INVOICE_ITEM_SUCCEEDED = 'UPDATING_INVOICE_ITEM_SUCCEEDED'
export const UPDATING_INVOICE_ITEM_FAILED = 'UPDATING_INVOICE_ITEM_FAILED'

export const DELETING_INVOICE_ITEM = 'DELETING_INVOICE_ITEM'
export const DELETING_INVOICE_ITEM_SUCCEEDED = 'DELETING_INVOICE_ITEM_SUCCEEDED'
export const DELETING_INVOICE_ITEM_FAILED = 'DELETING_INVOICE_ITEM_FAILED'

export const LOADING_USERS = 'LOADING_USERS'
export const LOADING_USERS_SUCCEEDED = 'LOADING_USERS_SUCCEEDED'
export const LOADING_USERS_FAILED = 'LOADING_USERS_FAILED'

export const CREATING_USER = 'CREATING_USER'
export const CREATING_USER_SUCCEEDED = 'CREATING_USER_SUCCEEDED'
export const CREATING_USER_FAILED = 'CREATING_USER_FAILED'

export const UPDATING_USER = 'UPDATING_USER'
export const UPDATING_USER_SUCCEEDED = 'UPDATING_USER_SUCCEEDED'
export const UPDATING_USER_FAILED = 'UPDATING_USER_FAILED'

export const DELETING_USER = 'DELETING_USER'
export const DELETING_USER_SUCCEEDED = 'DELETING_USER_SUCCEEDED'
export const DELETING_USER_FAILED = 'DELETING_USER_FAILED'
